
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: tetris-ever-mixer
  version: '20.21.12' # just for humans, typically '1.2+git' or '1.3.2'
  summary: A simple tetris game is written with C, and is rendered by SDL2. # 79 char long summary
  description: |
    **available key control for pure keyboard:**
    * Esc - Quit current scenes.
    * Q - Same as above.
    * up - rotate rock.
    * down - control rock fall down.
    * left - control rock to left.
    * right - control rock to right.
    * M - toggle mute.
    * H - halt music.
    * 9 - volume down.
    * 0 - volume up.

    _More detail please view code: < https://github.com/Joker2770/Tetris-ever-mixer >._

  # icon: snap/gui/icon.png

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots
  # base: core20

  ### core18 for i386
  base: core18
  # architectures:
    # - build-on: i386
      # run-on: i386

  plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
    gtk-3-themes:
      interface: content
      target: $SNAP/data-dir/themes
      default-provider: gtk-common-themes
    icon-themes:
      interface: content
      target: $SNAP/data-dir/icons
      default-provider: gtk-common-themes
    sound-themes:
      interface: content
      target: $SNAP/data-dir/sounds
      default-provider: gtk-common-themes
  
  apps:
    tetris-ever-mixer:
      command-chain: ["snap/command-chain/alsa-launch"]
      command: usr/local/bin/Tetris-ever-mixer
      environment:
        # pulseaudio
        LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
        # ALSA_CONFIG_PATH: ${SNAP}/etc/asound.conf
        # PULSE_SYSTEM: 1
        # PULSE_RUNTIME_PATH: /var/run/pulse
        # PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native
      extensions: [gnome-3-28]
      plugs:
        - audio-playback
        - pulseaudio
        - alsa
        - desktop
        - desktop-legacy
        - wayland
        - unity7
        - x11
        - gsettings
        
  layout:
    /usr/local/bin/bb3273.ttf:
      bind-file: $SNAP/usr/local/bin/bb3273.ttf
    /usr/local/bin/tetrisb.mid:
      bind-file: $SNAP/usr/local/bin/tetrisb.mid
    /usr/share/midi/freepats:
      bind: $SNAP/usr/share/midi/freepats
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
      bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
    /usr/share/alsa:
      bind: $SNAP/usr/share/alsa
    /etc/timidity:
      bind: $SNAP/etc/timidity
    /etc/fonts:
      bind: $SNAP/etc/fonts
    
  parts:
    alsa-mixin:
      plugin: dump
      source: https://github.com/diddlesnaps/snapcraft-alsa.git
      source-subdir: snapcraft-assets
      build-packages:
        - libasound2-dev
      stage-packages:
        - libasound2
        - libasound2-plugins
        - yad

    tetris-ever-mixer:
      after: [alsa-mixin]
      plugin: cmake
      source: "https://github.com/Joker2770/Tetris-ever-mixer.git"
      source-depth: 1
      source-branch: main
      source-type: git
      build-packages:
        - gcc
        - g++
        - cmake
        - make
        - libsdl2-dev
        - libsdl2-ttf-dev
        - libsdl2-mixer-dev
  
      stage-packages:
        - libsdl2-2.0-0
        - libsdl2-ttf-2.0-0
        - libsdl2-mixer-2.0-0
        - freepats
        - libmodplug1
        - libopusfile0
        - libpulse0
        - libsndfile1
