
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: tetris-ever-mixer
  version: '20.21.02.17' # just for humans, typically '1.2+git' or '1.3.2'
  summary: a simple tetris game writen with C, and be render by SDL2. # 79 char long summary
  description: |
    **available key control for pure keyboard:**
    * Esc - Quit current scenes.
    * Q - Same as above.
    * up - rotate rock.
    * down - control rock fall down.
    * left - control rock to left.
    * right - control rock to right.
    * 9 - play/pause the music.
    * 0 - halt music.

    _More detail please view code: < https://github.com/Joker2770/Tetris-ever-mixer >. _

  # icon: snap/gui/icon.png

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots
  base: core20
  
  apps:
    tetris-ever-mixer:
      command-chain: ["snap/command-chain/alsa-launch"]
      command: usr/local/bin/Tetris-ever-mixer
      # desktop: tetris-ever-mixer.desktop
      environment:
        # pulseaudio
        LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
        # ALSA_CONFIG_PATH: ${SNAP}/etc/asound.conf
        # PULSE_SYSTEM: 1
        # PULSE_RUNTIME_PATH: /var/run/pulse
        # PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native
      plugs:
        - audio-playback
        - pulseaudio
        - alsa
        - desktop
        - desktop-legacy
        - wayland
        - unity7
        
  layout:
    /usr/local/bin/bb3273.ttf:
      bind-file: $SNAP/usr/local/bin/bb3273.ttf
    /usr/local/bin/tetrisb.mid:
      bind-file: $SNAP/usr/local/bin/tetrisb.mid
    /usr/share/midi/freepats:
      bind: $SNAP/usr/share/midi/freepats
    /etc/timidity:
      bind: $SNAP/etc/timidity
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
      bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
    /usr/share/alsa:
      bind: $SNAP/usr/share/alsa
    
  parts:
    alsa-mixin:
      plugin: dump
      source: https://github.com/diddlesnaps/snapcraft-alsa.git
      source-subdir: snapcraft-assets
      build-packages:
        - libasound2-dev
      stage-packages:
        - libasound2
        - libasound2-plugins
        - yad

    tetris-ever-mixer:
      after: [alsa-mixin]
      plugin: cmake
      source: "https://github.com/Joker2770/Tetris-ever-mixer.git"
      source-depth: 1
      source-branch: main
      source-type: git
      build-packages:
        - gcc
        - g++
        - cmake
        - make
        - libsdl2-dev
        - libsdl2-ttf-dev
        - libsdl2-mixer-dev
  
      stage-packages:
        - libsdl2-2.0-0
        - libsdl2-ttf-2.0-0
        - libsdl2-mixer-2.0-0
        - libfluidsynth2
        - freepats
        - libmodplug1
        - libopusfile0
        - libpulse0
        - libsndfile1
        - libasound2
        - libasound2-plugins
        - libvorbis0a
        - libvorbisfile3
        - libvorbisenc2
        # - libxcursor1
        # - libxi6
        # - libxinerama1
        # - libxkbcommon0
        # - libxrandr2
        # - libxrender1
        # - libxss1
        # - libxcb1
        # - libxau6
        # - libxdmcp6
        # - libfreetype6
        # - libasyncns0
        # - libflac8
        # - libmpg123-0
        # - libogg0
        # - alsa-utils
        # - timidity
        # - timgm6mb-soundfont
