
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: tetris-ever-mixer
  version: '20.21.02.14' # just for humans, typically '1.2+git' or '1.3.2'
  summary: a simple tetris game writen with C, and be render by SDL2. # 79 char long summary
  description: |
    **available key control for pure keyboard:**
    * Esc - Quit current scenes.
    * Q - Same as above.
    * up - rotate rock.
    * down - control rock fall down.
    * left - control rock to left.
    * right - control rock to right.
    * 9 - play/pause the music.
    * 0 - halt music.

    _More detail please view code: < https://github.com/Joker2770/Tetris-ever-mixer >. _

  # icon: snap/gui/icon.png

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots
  base: core18
  
  apps:
    tetris-ever-mixer:
      command: usr/local/bin/Tetris-ever-mixer
      # desktop: tetris-ever.desktop
      plugs:
        - audio-playback
        - pulseaudio
        - alsa
        - desktop
        - desktop-legacy
        - wayland
        - unity7
        # - opengl
        
  layout:
    /usr/local/bin/bb3273.ttf:
      bind-file: $SNAP/usr/local/bin/bb3273.ttf
    /usr/local/bin/Aaron-19-Tetris-YANGS-remix.mp3:
      bind-file: $SNAP/usr/local/bin/Aaron-19-Tetris-YANGS-remix.mp3
    
  parts:
    tetris-ever-mixer:
      # after:
        # - desktop-glib-only
      plugin: cmake
      source: "https://github.com/Joker2770/Tetris-ever-mixer.git"
      source-depth: 1
      source-branch: main
      source-type: git
      build-packages:
        - gcc
        - cmake
        - make
        - libsdl2-dev
        - libsdl2-ttf-dev
        - libsdl2-mixer-dev
  
      stage-packages:
        - libsdl2-2.0-0
        - libsdl2-ttf-2.0-0
        - libsdl2-mixer-2.0-0
        # - pulseaudio
        # - pulseaudio-utils
        # - libsndfile1
        # - libxcb1
        # - libasyncns0
        # - libflac8
        - libmpg123-0
        # - libvorbisenc2
        # - libxau6
        # - libxdmcp6
        # - libogg0
        # - libvorbis0a
        # - libvorbisfile3
        # - timgm6mb-soundfont
        # - libgl1-mesa-glx
        # - libglu1-mesa
